debian/extra/90plasmadiscover /etc/apt/apt.conf.d/
usr/bin/plasma-discover
usr/lib/*/libexec/kf5/discover/runservice
usr/lib/*/plasma-discover/*
usr/lib/*/qt5/plugins/discover-notifier/*
usr/lib/*/qt5/plugins/discover/*
usr/lib/*/qt5/qml/org/kde/discover/*
usr/lib/*/qt5/qml/org/kde/discovernotifier/libDiscoverNotifierDeclarativePlugin.so
usr/lib/*/qt5/qml/org/kde/discovernotifier/qmldir
usr/share/applications/*
usr/share/knotifications5/*
usr/share/kservices5/*
usr/share/metainfo/*
usr/share/plasma/plasmoids/*
